import { BookType } from "./types";



export const demoBooks: BookType[] = [
  {
    _id: 'demo-1',
    title: 'The Great Gatsby',
    caption: 'A classic novel about the American Dream. This is demo data shown when the API is unavailable.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Demo Author', profileImage: '' },
    link: 'https://example.com/book-link',
    createdAt: new Date().toISOString(),
    genre: 'Fiction',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-2',
    title: 'Sapiens: A Brief History of Humankind',
    caption: 'An insightful exploration of human history. Demo content for testing purposes.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Demo Reviewer', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Non-Fiction',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-3',
    title: '1984',
    caption: 'A dystopian social science fiction novel exploring themes of totalitarianism and surveillance.',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Classic Reader', profileImage: '' },
    link: 'https://example.com/1984',
    createdAt: new Date().toISOString(),
    genre: 'Science Fiction',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-4',
    title: 'To Kill a Mockingbird',
    caption: 'A powerful story of racial injustice and moral growth in the American South.',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Literature Fan', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Drama',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-5',
    title: 'The Hobbit',
    caption: 'An epic fantasy adventure following Bilbo Baggins on his unexpected journey.',
    image: 'https://images.unsplash.com/photo-1518373714866-3f1478910cc0?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Fantasy Enthusiast', profileImage: '' },
    link: 'https://example.com/hobbit',
    createdAt: new Date().toISOString(),
    genre: 'Fantasy',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-6',
    title: 'Pride and Prejudice',
    caption: 'Jane Austen\'s beloved romantic novel about Elizabeth Bennet and Mr. Darcy.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Romance Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Romance',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-7',
    title: 'The Catcher in the Rye',
    caption: 'J.D. Salinger\'s coming-of-age story about teenage rebellion and alienation.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: '3',
    user: { name: 'Young Adult Fan', profileImage: '' },
    link: 'https://example.com/catcher',
    createdAt: new Date().toISOString(),
    genre: 'Coming-of-Age',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-8',
    title: 'Dune',
    caption: 'Frank Herbert\'s epic space opera about politics, religion, and ecology on a desert planet.',
    image: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Sci-Fi Master', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Science Fiction',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-9',
    title: 'The Lord of the Rings',
    caption: 'Tolkien\'s masterpiece fantasy trilogy about the quest to destroy the One Ring.',
    image: 'https://images.unsplash.com/photo-1518373714866-3f1478910cc0?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Epic Fantasy Lover', profileImage: '' },
    link: 'https://example.com/lotr',
    createdAt: new Date().toISOString(),
    genre: 'Fantasy',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-10',
    title: 'Harry Potter and the Philosopher\'s Stone',
    caption: 'J.K. Rowling\'s magical tale of a young wizard discovering his destiny.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Magic Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Fantasy',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-11',
    title: 'Brave New World',
    caption: 'Aldous Huxley\'s dystopian vision of a society controlled by technology and conditioning.',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Dystopia Explorer', profileImage: '' },
    link: 'https://example.com/brave-new-world',
    createdAt: new Date().toISOString(),
    genre: 'Science Fiction',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-12',
    title: 'The Alchemist',
    caption: 'Paulo Coelho\'s philosophical novel about following your dreams and personal legend.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Philosophy Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Philosophy',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-13',
    title: 'Gone Girl',
    caption: 'Gillian Flynn\'s psychological thriller about a marriage gone terribly wrong.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Thriller Fan', profileImage: '' },
    link: 'https://example.com/gone-girl',
    createdAt: new Date().toISOString(),
    genre: 'Thriller',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-14',
    title: 'The Da Vinci Code',
    caption: 'Dan Brown\'s fast-paced mystery thriller involving secret societies and religious history.',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    rating: '3',
    user: { name: 'Mystery Solver', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Mystery',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-15',
    title: 'Educated',
    caption: 'Tara Westover\'s powerful memoir about education, family, and self-discovery.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Memoir Reader', profileImage: '' },
    link: 'https://example.com/educated',
    createdAt: new Date().toISOString(),
    genre: 'Memoir',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-16',
    title: 'The Girl with the Dragon Tattoo',
    caption: 'Stieg Larsson\'s gripping crime novel featuring hacker Lisbeth Salander.',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Crime Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Crime',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-17',
    title: 'Becoming',
    caption: 'Michelle Obama\'s inspiring memoir about her journey from childhood to the White House.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    rating: '5',
    user: { name: 'Biography Enthusiast', profileImage: '' },
    link: 'https://example.com/becoming',
    createdAt: new Date().toISOString(),
    genre: 'Biography',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-18',
    title: 'The Hunger Games',
    caption: 'Suzanne Collins\' dystopian YA novel about survival and rebellion in Panem.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'YA Enthusiast', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Young Adult',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-19',
    title: 'The Kite Runner',
    caption: 'Khaled Hosseini\'s emotional story of friendship, guilt, and redemption in Afghanistan.',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'World Literature Fan', profileImage: '' },
    link: 'https://example.com/kite-runner',
    createdAt: new Date().toISOString(),
    genre: 'Historical Fiction',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-20',
    title: 'Atomic Habits',
    caption: 'James Clear\'s practical guide to building good habits and breaking bad ones.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Self-Help Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Self-Help',
    mediaType: 'post' as const,
  },
  {
    _id: 'demo-21',
    title: 'The Silent Patient',
    caption: 'Alex Michaelides\' psychological thriller about a woman who refuses to speak.',
    image: 'https://images.unsplash.com/photo-1518373714866-3f1478910cc0?w=400&h=600&fit=crop',
    rating: '4',
    user: { name: 'Psychological Thriller Fan', profileImage: '' },
    link: 'https://example.com/silent-patient',
    createdAt: new Date().toISOString(),
    genre: 'Thriller',
    mediaType: 'video' as const,
  },
  {
    _id: 'demo-22',
    title: 'Where the Crawdads Sing',
    caption: 'Delia Owens\' mystery novel about a girl who grows up isolated in the marshes.',
    image: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=400&h=600&fit=crop',
    rating: '3',
    user: { name: 'Nature Mystery Reader', profileImage: '' },
    link: '',
    createdAt: new Date().toISOString(),
    genre: 'Mystery',
    mediaType: 'post' as const,
  }
];